blog/urls.py
#this urls.py file connects the views and templates together in the website.

from django.urls import path
from .views import home,about, like_post, favorite_post, post_favorite_list
from .views import (
	PostListView,
	PostDetailView,
	PostCreateView,
	PostUpdateView,
	PostDeleteView,
	UserPostListView
)



app_name = "blog"
urlpatterns = [
	# path('home/',home, name="blog-home"),  # this is for functional based views
	path('home/', PostListView.as_view(), name="blog-home"), #this is for class based views
	path('', PostListView.as_view(), name="blog-home"),
	path('home/user/<str:username>/', UserPostListView.as_view(), name="user-posts"),
	path('post/<int:pk>/', PostDetailView.as_view(), name="post-detail"),
	path('post/<int:pk>/update/', PostUpdateView.as_view(), name="post-update"),
	path('post/<int:pk>/delete/', PostDeleteView.as_view(), name="post-delete"),
	path('post/<int:pk>/favorite_post/', favorite_post, name="favorite_post"),
	path('post/new/', PostCreateView.as_view(), name="post-create"),
	path('about/',about, name="blog-about"),
	path('like/',like_post, name="like_post"),
	path('favorites', post_favorite_list, name='post_favorite_list'),

]

django_corey_schafer/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',auth_views.LoginView.as_view(template_name="users/login.html"), name="login-page"),
    path('logout/',auth_views.LogoutView.as_view(template_name="users/logout.html"), name="logout-page"),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name="users/password_reset.html"),
        name="password_reset"),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html"),
        name="password_reset_confirm"),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
        name="password_reset_complete"),
    path('users/',include('users.urls')),
    #path('profile',user_views.profile, name="profile-page"),
    path('',include('blog.urls')),
    path('blog/',include('blog.urls')),
    path('oauth/', include('social_django.urls', namespace="social")),
] #  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) either u could do like this when ur settings.DEBUG == True by default or

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import profile,SignUpView, ActivateAccount





app_name = "users"
urlpatterns = [
    # path('register/',register, name = "register-page" ), #for using this first import register in from .views
    path('register/', SignUpView.as_view(), name='register-page'),
    path('activate/<uidb64>/<token>/', ActivateAccount.as_view(), name='activate'),
    path('profile/',profile, name = "profile-page" ),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from .validators import validate_file_size

# Create your models here.

#this models.py file means realtional table or schema in the databse and title, content etc are fields in the database table just like in sql. 

class Post(models.Model):
	title 		= models.CharField(max_length = 120)
	content 	= models.TextField()
	date_posted = models.DateTimeField(default = timezone.now) #this will show on which date the post was created.
	author 		= models.ForeignKey(User, on_delete=models.CASCADE) #this means if user got deleted then the authr will get deleted but not vice versa.
	image 		= models.ImageField( default="default1.jpg", upload_to = "profile_pics", blank =True,null =True) #and this allow images to get uploaded in the post and upload_to means in which folder all the files have been saved. 
	likes 		= models.ManyToManyField(User, related_name='likes', blank=True) #it means that one post can have many likes and many posts can have many likes 
	video		= models.FileField(upload_to='profile_vids', blank=True, null=True, validators=[validate_file_size]) # this is used for uploading video or documents likep pdf in the post.
	restrict_comments = models.BooleanField(default=False) #this means that we want posts to allow comments on it or not.
	favorite 	= models.ManyToManyField(User, related_name="favorite", blank=True) #same as likes

	def __str__(self):
		return self.title

	def total_likes(self):
		return self.likes.count()

	#this function means in post-detail template where we want our users to redirect after clicking on post's title in the website.
	def get_absolute_url(self):
		return reverse('blog:post-detail', kwargs={'pk' : self.pk})

	

class Comment(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE) #this means that if post is deleted then all comments will get deleted also but if comments got deleted then post wil not get deleted obviously. 
	user = models.ForeignKey(User, on_delete=models.CASCADE) # same as above if user got deleted then all comments will get deleted but not vive versa. 
	comment = models.TextField(max_length=160)
	reply = models.ForeignKey('Comment', null = True, related_name='replies', on_delete=models.CASCADE,blank =True)
	timestamp = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return '{}-{}'.format(self.post.title, str(self.user.username))

blog/forms.py
from django import forms
from .models import Post, Comment
from users.models import Profile
from django.contrib.auth.models import User



class CommentModelForm(forms.ModelForm):
	comment = forms.CharField(label="", widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Comment here!', 'rows': '3', 'cols': '50'}))
	class Meta:
		model = Comment
		fields = ['comment']

blog/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.contrib import messages 
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic import (
		ListView,
		DetailView,
		CreateView,
		UpdateView,
		DeleteView,
)
from .models import Post, Comment
from .forms import CommentModelForm
from django.urls import reverse_lazy
# from django.core.exceptions import ValidationError
# from django import forms

#Create your views here.
#This was dummy data that we had created to show data on the website. but not recommended because we will use the databse itself to load the data in the website.
# posts = [
# 	{
# 	'author':'Parth Lashkari',
# 	'title':'Blog Post 1',
# 	'content':'First Post Content',
# 	'date_posted':'July-2019-13'
# 	},
# 	{
# 	'author':'Yatharth Lashkari',
# 	'title':'Blog Post 2',
# 	'content':'Second Post Content',
# 	'date_posted':'July-2019-14'
# 	}
# ]
# These are fucntional based views
def home(request):
	context = {
		'posts': Post.objects.all()
	}
	return render(request,"blog/home.html",context)

# These are custom class based views not conventional and LoginRequiredMixin means that user shoud be logged in to see the home page of website and ListView means that on our home page posts' list will be shown to user.
class PostListView(LoginRequiredMixin, ListView):
	model 				= Post
	template_name 		= 'blog/home.html' #(if we dont write this here then django will look into the default template with naming convention like this <app>/<model>_<viewtype>.html which we have to create manually other than our home.html page so always try to write 'template_name' when using class based views when not using conventional template.)
	context_object_name = 'posts' #(this is the customised name of object that we are using from above home functional based view but by default class based views use the name of object as object itself that we can see in post_detail.html templates in blog app.)
	ordering 			= ['-date_posted'] #this means we want the latest post to be shown on the top and oldest on the bottom and if we remove the hyphen sign reverse will happen
	paginate_by	= 5

class UserPostListView(LoginRequiredMixin, ListView): #this page will shown the particular users all posts when any user click on the username of post.
	model 				= Post
	template_name 		= 'blog/user_posts.html' 
	context_object_name = 'posts'  
	#ordering 			= ['-date_posted'] # we dont need it coz we r overriding it in get_query_set function below.
	paginate_by	= 5

	def get_queryset(self): #this will take the username from the url of website and get_object_or_404  means get the object or user or show 404 error if user not there.
		user = get_object_or_404(User, username = self.kwargs.get('username'))
		return Post.objects.filter(author = user).order_by('-date_posted')

# now we are creating the conventional class based view 
class PostDetailView(LoginRequiredMixin, DetailView):
	model = Post
	fields = ['title', 'content','video', 'image'] #this here means that what fields we want to show on the postdetailview page.
	form_class = CommentModelForm #this will use this form from the forms.py file
	
	# now we r not using template_name in it instead of it we r created conventional template named <app>/<model>_<viewtype>.html or in this case blog/post_detail.html so we r going to create this template in our blog templates 
	def get_context_data(self, **kwargs): #this will load the contexts in the html page 
		context = super().get_context_data(**kwargs)
		is_liked = False
		is_favorite = False
		if self.object.likes.filter(id = self.request.user.id).exists():
			is_liked = True

		if self.object.favorite.filter(id = self.request.user.id).exists():
			is_favorite = True

		context['comments'] = Comment.objects.filter(post=self.object,reply=None).order_by('-timestamp')[:1000]
		context['form'] = CommentModelForm()
		context['comment_form'] = CommentModelForm()
		context['is_liked'] = is_liked
		context['is_favorite'] = is_favorite
		context['post'] = self.request.user
		context['total_likes'] = self.object.total_likes()

		return context

	def post(self, request, *args, **kwargs):
		self.object = self.get_object()
		

		# post = get_object_or_404(Post)
		# form = self.get_form()
		# if form.is_valid():
		#     return self.form_valid(form)
		# else:
		#     return self.form_invalid(form)
		if request.method == "POST":
			comment_form = CommentModelForm(request.POST or None)
			if comment_form.is_valid():
				comment = request.POST.get('comment')
				reply_id = request.POST.get('comment_id')
				comment_qs = None
				if reply_id:
					comment_qs = Comment.objects.get(id = reply_id)
				comments = Comment.objects.create(post=self.object, user =request.user, comment=comment, reply=comment_qs)
				comments.save()
				#success_url = reverse_lazy(post.get_absolute_url())

				return redirect(self.object.get_absolute_url())
		else:
			comment_form = CommentModelForm()

	def form_valid(self, form): #this will check if form data which is filled by user is valid or not.
		form.instance.article = self.object
		# form.save()
		return super().form_valid(form)
	# if request.method == "POST":
	# 	comment_form = CommentModelForm(request.POST or None)
	# 	if comment_form.is_valid():
	# 		comment = request.POST.get('comment')
	# 	else:
	# 		comment_form = CommentModelForm()

def like_post(request):
	post = get_object_or_404(Post, id=request.POST.get('post_id'))
	is_liked = False
	if post.likes.filter(id=request.user.id).exists():
		post.likes.remove(request.user)
		is_liked = False
	else:
		post.likes.add(request.user)
		is_liked = True
	return redirect(post.get_absolute_url())

def post_favorite_list(request):
	user = request.user
	favorite_posts = user.favorite.all()
	context = {
		'favorite_posts':favorite_posts,
	}
	return render(request, 'blog/post_favorite_list.html', context)

def favorite_post(request, pk):
	post = get_object_or_404(Post, pk=pk)
	if post.favorite.filter(id=request.user.id).exists():
		post.favorite.remove(request.user)
		is_liked = False
	else:
		post.favorite.add(request.user)
	return redirect(post.get_absolute_url())


class PostCreateView(LoginRequiredMixin, CreateView): #when user clicks on the new post in the website then this page will be shown
	#both createview,updateview share the post_form.html template that's why i haven't created explicitly the template_name like other views.and post_form.htm means modelname_form.html.
	model  = Post
	fields = ['title', 'content','video', 'image', 'restrict_comments']
	success_url = reverse_lazy('blog:blog-home') #it is useful when after creating new post u want to redirect to the blog-home page otherwise in models.py get_absolute_url will make u redirect to the post_detail.html page or post-detail page and if u define both then success-url will dominate the get-absolute_url

	def form_valid(self, form):
		form.instance.author = self.request.user
		# image = form.cleaned_data.get('image')
		# video = form.cleaned_data.get('video')
		# if form.instance.image and form.instance.video:
		# 	# messages.error(self.request, f'no')
		# 	raise forms.ValidationError("u cant post ")
		# 	return redirect('blog:post-create')
		# form.save()
		messages.success(self.request, f'Your new post has been successfully created') #if the new post has been successfully created then this message will be shown on the website.
		return super().form_valid(form)
	def form_invalid(self, form):
		messages.warning(self.request, f'Please correct the error below')
		return super().form_invalid(form)

# UserPassesTestMixin will check no other user can update the post if the post has not been made by that user. 
class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView): #when users click on the update button on the post then this page will load.
	model  = Post
	fields = ['title', 'content', 'video', 'image', 'restrict_comments']
	success_url = reverse_lazy('blog:blog-home') 

	def form_valid(self, form):
		form.instance.author = self.request.user
		return super().form_valid(form)

	def test_func(self): #this function is used when UserPassesTestMixin is used. 
		post = self.get_object()
		if self.request.user == post.author: #this will check if the login user and the and the post author(means the post owner) are same or not.
			return True
		return False

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView): #if we didnt define template_name explicitly then we have to create modelname_confirm_delete.html template and in our case post_confirm_delete.html
	model = Post
	success_url = reverse_lazy('blog:blog-home')

	def test_func(self):
		post = self.get_object()
		if self.request.user == post.author:
			return True
		return False

def about(request):
	return render(request,"blog/about.html",{'title':'About'})

blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% block content %}

	<h1> About Page of Blog</h1>

{% endblock content %}

blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% block content %}
	
	{% for post in posts %}
		<article class="media content-section  col-xs-6">
			<img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
		  <div class="media-body">
		    <div class="article-metadata">
		      <a class="mr-2" href="{% url 'blog:user-posts' post.author.username %}">{{ post.author }}</a>
		      <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
		    </div>
		    <h2><a class="article-title" href="{% url 'blog:post-detail' post.id %}">{{ post.title }}</a></h2>
		    <p class="article-content">{{ post.content }}</p>
		    <!-- <img src="{{ post.image.url }}" class="img-fluid" alt="Responsive image"> -->
		    {% if not post.video and  post.image == 'default1.jpg' %}
		    

		    {% elif post.video and post.image %}
		    
				<!-- <video width="600" height="400" controls>
					<source src="{{ post.video.url }}" type="video/mp4">
					Your browser does not support the video tag.
				</video> -->

				<div class="embed-responsive embed-responsive-16by9">
				  <iframe class="embed-responsive-item" src="{{ post.video.url }}" allowfullscreen></iframe>
				</div>
				


			{% else %}


			    <img src="{{ post.image.url }}" class="img-fluid" alt="Responsive image">

			

			{% endif %}






		</div>
		</article>
	{% endfor %}

	{% if is_paginated %}

		{%if page_obj.has_previous %}
			<a class= "btn btn-outline-info mb-4" href="?page=1">First</a>
			<a class= "btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
		{% endif %}

		{% for num in page_obj.paginator.page_range %}
			{% if page_obj.number == num %}
				<a class= "btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
			{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
				<a class= "btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
			{% endif %}

		{% endfor %}

		{% if page_obj.has_next %}
			<a class= "btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
			<a class= "btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
		{% endif %}

	{% endif %}

{% endblock content %}

blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base1.html' %}
{% block content %}
	<!-- <h1> Hello this is my second django site project</h1> -->

	<div class = 'content-section' >
		<form action = "" method = "POST">{% csrf_token %}
			<fieldset class ="form-group">
				<legend class ="border-bottom mb-4">
					Delete Post
				</legend>
				<h2>Are you sure, you want to delete this post? "{{ object.title }}"</h2>
				

			</fieldset>
			<div class="form-group">
			<button class="btn btn-outline-danger" type = "submit">Yes, Delete</button>	
			<a class="btn btn-outline-secondary" href="{% url 'blog:post-detail' object.id %}">Cancel</a>	
			</div>	
		</form>
		

	</div>

{% endblock content %}

blog/templates/blog/post_detail.html
{% extends 'blog/base1.html' %}
{% load crispy_forms_tags %}
{% block content %}	
	<article class="media content-section col-xs-6">
		<img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}">
	  <div class="media-body">
	    <div class="article-metadata">
	      <a class="mr-2" href="{% url 'blog:user-posts' object.author.username %}">{{ object.author }}</a>
	      <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>
	      {% if object.author == user %}
	      	<div>
	      		<a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'blog:post-update' object.id %}">Update</a>
	      	<a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'blog:post-delete' object.id %}">Delete</a>
	      	</div>
	      {% endif %}
	    </div>
	    <h2 class="article-title">{{ object.title }}</h2>
	    <p class="article-content">{{ object.content }}</p>
	    <!-- <img src="{{ object.image.url }}" class="img-fluid" alt="Responsive image"> -->
	<!--     {% if object.video %}
    <video width="600" height="400" controls>
        <source src="{{ object.video.url }}" type="video/mp4">
        Your browser does not support the video tag.
    </video>


{% else %}

    <img src="{{ object.image.url }}" class="img-fluid" alt="Responsive image">
{% endif %} -->
	    
		{% if not object.video and  object.image == 'default1.jpg' %}
	    

	    {% elif object.video and object.image %}
	    
			<!-- <video width="600" height="400" controls>
				<source src="{{ object.video.url }}" type="video/mp4">
				Your browser does not support the video tag.
			</video> -->

			<div class="embed-responsive embed-responsive-16by9">
				  <iframe class="embed-responsive-item" src="{{ object.video.url }}" allowfullscreen></iframe>
			</div>

		{% else %}


		    <img src="{{ object.image.url }}" class="img-fluid" alt="Responsive image">
		{% endif %}

		    
	  </div>
	</article>
	{% if request.user.is_authenticated %}
	{{ total_likes }} Like{{ total_likes|pluralize }}
	<form action="{% url 'blog:like_post' %}" method="POST" >{% csrf_token %}
		{% if is_liked %}
			<!-- <button  type="submit" name="post_id" value="{{ object.id }}" class="btn btn-danger">Dislike</button> -->
			<button  type="submit" name="post_id" value="{{ object.id }}" class="btn btn-outline-danger"><i class="fas fa-thumbs-down fa-lg"></i></button>
		{% else %}
			<button  type="submit" name="post_id" value="{{ object.id }}" class="btn btn-outline-primary"><i class="fas fa-thumbs-up fa-lg ml-1"></i></button>
			<!-- <button  type="submit" name="post_id" value="{{ object.id }}" class="btn btn-primary">Like</button> -->
		{% endif %}
		</form>
		{% endif %}


	
	<hr>


	<div id="favorite-section">
		{% if is_favorite %}
			<a href="{% url 'blog:favorite_post' pk=object.pk %}">
				<i class="fas fa-heart fa-lg " style="color:red !important;" ><small class="ml-1" style="color:black !important;,font-style: helvetica;">Favorite</small></i>
			</a>
		{% else %}
			<a href="{% url 'blog:favorite_post' pk=object.pk %}">
			<i class="far fa-heart fa-lg" style="color:red !important;"></i>
			</a>
		{% endif %}
	</div>

	<br>
	<br>
	
	{% if not object.restrict_comments %}
	<div class="main-comment-section">
		<div class="container-fluid mt-2">
			<div class="form-group row">
				<form  method="POST" >{% csrf_token %}
					{{ comment_form|crispy }}
					<i class="fa fa-comment-o fa-lg btn btn-outline-success" aria-hidden="true"></i>
					{% if request.user.is_authenticated %}
						<input type="submit" value="Post Comment" class="btn btn-outline-success">
					{% else %}
						<input type="submit" value="Post Comment" class="btn btn-outline-success" disabled>
					{% endif %}
				</form>
			</div>
		</div>


		{{ comments.count }} Comment{{ comments|pluralize }}
		{% for comment in comments %}
		<blockquote class="blockquote">
			<p class="mb-0"><small>{{ comment.comment }}</small></p>
			<footer class="blockquote-footer">
				<small> by <cite title="Source Title">{{ comment.user|capfirst }}</cite></small>
				<i class="fa fa-comment-o fa-lg ml-1 btn btn-outline-dark btn-sm" aria-hidden="true"></i>
				<button type="button" name="button" class="reply-btn btn btn-outline-dark btn-sm ml-0">
					Reply
				</button>
			</footer>
		</blockquote>

		<div class="replied-comments container mt-2" style="display:none;">
			{% for reply in comment.replies.all %}
				<blockquote class="blockquote">
					<p class="mb-0"><small>{{ reply.comment }}</small></p>
					<footer class="blockquote-footer">
						<small>by <cite title="Source Title">{{ reply.user|capfirst }}</cite></small>
					</footer>
				</blockquote>
			{% endfor %}
			<div class="form-group row">
				<form  method="POST" >{% csrf_token %}
					<input type="hidden" name="comment_id" value="{{ comment.id }}">
					{{ comment_form|crispy }}
					{% if request.user.is_authenticated %}
						<input type="submit" value="Post Reply" class="btn btn-outline-success">
					{% else %}
						<input type="submit" value="Post Reply" class="btn btn-outline-success" disabled>
					{% endif %}
				</form>	
			</div>
		</div>

		{% endfor %}


	</div>
	{% endif %}
{% endblock content %}

blog/templates/blog/post_favorite_list.html
{% extends 'blog/base1.html' %}
{% block content %}
<div class="container-fluid" style="margin-left: 23%;">
{% for post in favorite_posts %}
		<article class="media content-section">
			<img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
		  <div class="media-body">
		    <div class="article-metadata">
		      <a class="mr-2" href="{% url 'blog:user-posts' post.author.username %}">{{ post.author }}</a>
		      <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
		    </div>
		    <h2><a class="article-title" href="{% url 'blog:post-detail' post.id %}">{{ post.title }}</a></h2>
		    <p class="article-content">{{ post.content }}</p>
		    <!-- <img src="{{ post.image.url }}" class="img-fluid" alt="Responsive image"> -->
		    {% if not post.video and  post.image == 'default1.jpg' %}
		    

		    {% elif post.video and post.image %}
		    
				<!-- <video width="600" height="400" controls>
					<source src="{{ post.video.url }}" type="video/mp4">
					Your browser does not support the video tag.
				</video> -->

				<div class="embed-responsive embed-responsive-16by9">
				  <iframe class="embed-responsive-item" src="{{ post.video.url }}" allowfullscreen></iframe>
			</div>
				


			{% else %}


			    <img src="{{ post.image.url }}" class="img-fluid" alt="Responsive image">
			{% endif %}


			{% empty %}
			<div class="mt-5">
				<h3>No Favorite Posts Found.&#128533; Please make some posts favorite for me.</h3>
			<hr>
			</div>


		</div>
		</article>
	{% endfor %}
</div>


{% endblock content %}

blog/templates/blog/post_form.html
{% extends 'blog/base1.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<!-- <h1> Hello this is my second django site project</h1> -->
	<div class="container-fluid" style="margin-left:23%;">
	<div class = 'content-section' >
		<form action = "" method = "POST" enctype="multipart/form-data" >{% csrf_token %}
			

			<fieldset class ="form-group"  >
				<legend class ="border-bottom mb-4">
					Create Post
				</legend>

				<legend class ="border-bottom mb-4">
					<div class="alert alert-info" role="alert">
			   <small> &#128400;Just for fun.You can choose either image or video or none of these to upload your post.Thanks&#128536;</small>
			</div>
				</legend>

				<!-- {{ form.as_p }} we were using this coding block when we dont use crispy forms -->
				{{ form|crispy }}



			</fieldset>
			
			<div class="form-group">
			<button class="btn btn-outline-info" type = "submit">Post</button>	
			</div>	
		</form>
		

	</div>
</div>

{% endblock content %}

blog/templates/blog/user_posts.html
{% extends 'blog/base1.html' %}
{% block content %}
	<h1 class="mb-3">Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1> <!-- to get the username from the url we use this coding block {{ view.kwargs.username }} and this {{ page_obj.paginator.count }}) means that how many posts this user posted till now.-->
	{% for post in posts %}
		<article class="media content-section col-xs-6">
			<img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
		  <div class="media-body">
		    <div class="article-metadata">
		      <a class="mr-2" href="{% url 'blog:user-posts' post.author.username %}">{{ post.author }}</a>
		      <!-- <a class="mr-2" href="#">{{ post.author }}</a> this link is alternative to the above link if u want to understand this href then uncomment this link and comment above link but dont comment both links. -->
		      <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
		    </div>
		    <h2><a class="article-title" href="{% url 'blog:post-detail' post.id %}">{{ post.title }}</a></h2>
		    <p class="article-content">{{ post.content }}</p>
		    <!-- <img src="{{ post.image.url }}" class="img-fluid" alt="Responsive image"> -->

	<!-- 	    {% if post.video %}
    <video width="600" height="400" controls>
        <source src="{{ post.video.url }}" type="video/mp4">
        Your browser does not support the video tag.
    </video>


{% else %}

    <img src="{{ post.image.url }}" class="img-fluid" alt="Responsive image">

{% endif %} -->
			

			{% if not post.video and  post.image == 'default1.jpg' %}
		    

		    {% elif post.video and post.image %}
		    
				<!-- <video width="600" height="400" controls>
					<source src="{{ post.video.url }}" type="video/mp4">
					Your browser does not support the video tag.
				</video> -->

				<div class="embed-responsive embed-responsive-16by9">
				  <iframe class="embed-responsive-item" src="{{ post.video.url }}" allowfullscreen></iframe>
				</div>

			{% else %}


			    <img src="{{ post.image.url }}" class="img-fluid" alt="Responsive image">
			{% endif %}

		  </div>
		</article>
	{% endfor %}
	{% if is_paginated %}

		{%if page_obj.has_previous %}
			<a class= "btn btn-outline-info mb-4" href="?page=1">First</a>
			<a class= "btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
		{% endif %}

		{% for num in page_obj.paginator.page_range %}
			{% if page_obj.number == num %}
				<a class= "btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
			{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
				<a class= "btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
			{% endif %}

		{% endfor %}

		{% if page_obj.has_next %}
			<a class= "btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
			<a class= "btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
		{% endif %}

	{% endif %}

{% endblock content %}