blog/urls.py
#this urls.py file connects the views and templates together in the website.

from django.urls import path
from .views import home,about, like_post, favorite_post, post_favorite_list
from .views import (
	PostListView,
	PostDetailView,
	PostCreateView,
	PostUpdateView,
	PostDeleteView,
	UserPostListView
)



app_name = "blog"
urlpatterns = [
	# path('home/',home, name="blog-home"),  # this is for functional based views
	path('home/', PostListView.as_view(), name="blog-home"), #this is for class based views
	path('', PostListView.as_view(), name="blog-home"),
	path('home/user/<str:username>/', UserPostListView.as_view(), name="user-posts"),
	path('post/<int:pk>/', PostDetailView.as_view(), name="post-detail"),
	path('post/<int:pk>/update/', PostUpdateView.as_view(), name="post-update"),
	path('post/<int:pk>/delete/', PostDeleteView.as_view(), name="post-delete"),
	path('post/<int:pk>/favorite_post/', favorite_post, name="favorite_post"),
	path('post/new/', PostCreateView.as_view(), name="post-create"),
	path('about/',about, name="blog-about"),
	path('like/',like_post, name="like_post"),
	path('favorites', post_favorite_list, name='post_favorite_list'),

]

django_corey_schafer/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',auth_views.LoginView.as_view(template_name="users/login.html"), name="login-page"),
    path('logout/',auth_views.LogoutView.as_view(template_name="users/logout.html"), name="logout-page"),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name="users/password_reset.html"),
        name="password_reset"),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html"),
        name="password_reset_confirm"),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
        name="password_reset_complete"),
    path('users/',include('users.urls')),
    #path('profile',user_views.profile, name="profile-page"),
    path('',include('blog.urls')),
    path('blog/',include('blog.urls')),
    path('oauth/', include('social_django.urls', namespace="social")),
] #  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) either u could do like this when ur settings.DEBUG == True by default or

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import profile,SignUpView, ActivateAccount





app_name = "users"
urlpatterns = [
    # path('register/',register, name = "register-page" ), #for using this first import register in from .views
    path('register/', SignUpView.as_view(), name='register-page'),
    path('activate/<uidb64>/<token>/', ActivateAccount.as_view(), name='activate'),
    path('profile/',profile, name = "profile-page" ),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image 


# Create your models here.
class Profile(models.Model):
	user 	= models.OneToOneField(User, on_delete = models.CASCADE)
	image 	= models.ImageField(default = "default.jpg", upload_to = "profile_pics")
	email_confirmed = models.BooleanField(default=False)


	

	def __str__(self):
		return f'{self.user.username} Profile'

	# def save(self, *args, **kwargs):
	# 	super().save(*args, **kwargs)

	# 	img = Image.open(self.image.path)

	# 	if img.height > 300 or img.width > 300:
	# 		output_size = (300, 300)
	# 		img.thumbnail(output_size)
	# 		img.save(self.image.path)

users/forms.py
#this forms.py is used for making forms in the django instead of in html and fields means that which field we want to show in the form and model measn which model i want to load in my forms.

from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from.models import Profile



class UserRegisterForm(UserCreationForm):
	CHOICES = [('M','Male'),('F','Female')]
	YEARS= [x for x in range(1940,2021)]
	email  = forms.EmailField(required=True, help_text='*Required. Please enter a valid email address.*',widget=forms.TextInput(attrs={'placeholder': 'myexample@gmail.com'}))
	gender = forms.ChoiceField(choices=CHOICES, label='Gender', widget=forms.RadioSelect)
	birth_date= forms.DateField(label='Birthday', initial="1990-06-21", widget=forms.SelectDateWidget(years=YEARS))



	class Meta:
		model = User
		fields = ['username', 'email', 'gender','birth_date', 'password1', 'password2']

class UserUpdateForm(forms.ModelForm):
	email = forms.EmailField()

	class Meta:
		model = User
		fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):

	class Meta:
		model = Profile
		# fields = ['gender', 'birth_date', 'image']
		fields = ['image']

users/views.py
from django.shortcuts import render, redirect
from django.views.generic import View, UpdateView
from django.urls import reverse_lazy
#from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages     #messages ke types = (messages.debug, message.success, messages.info, message.warning, messages.error)
from .forms import UserRegisterForm,UserUpdateForm,ProfileUpdateForm

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User


from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.template.loader import render_to_string


from django.contrib.auth import login
from django.contrib.auth.models import User
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from users.tokens import account_activation_token


# Create your views here.
# def register(request):
# 	if request.method == 'POST':
# 		#form = UserCreationForm(request.POST)
# 		form = UserRegisterForm(request.POST)
# 		if form.is_valid():
# 			form.save()
# 			username = form.cleaned_data.get('username')
# 			# we were using these below 2 lines when we hadn't created the login page. 
# 			# messages.success(request, f'Account created for {username}!')
# 			# return redirect('blog:blog-home')
# 			messages.success(request, f'Your account has been created! You are now able to login.')
# 			return redirect('login-page')
# 	else:
# 		#form = UserCreationForm()
# 		form = UserRegisterForm()
# 	return render(request, "users/register.html", {'form': form})


# Sign Up View
class SignUpView(View):
	form_class = UserRegisterForm
	template_name = 'users/register.html' #this will load this specifi  template for this view. 

	def get(self, request, *args, **kwargs): 
		form = self.form_class()
		return render(request, self.template_name, {'form': form})

	def post(self, request, *args, **kwargs):
		form = self.form_class(request.POST) #request.POST will check if form has been filled and submitted and if request.FILES wiil check if photo has been choosen and submitted.
		if form.is_valid():

			user = form.save(commit=False)
			user.is_active = False # Deactivate account till it is confirmed via email confirmation link when he registers for the first time.
			user.save()

			current_site = get_current_site(request)
			subject = 'Activate Your ParthBook Account'
			message = render_to_string('users/account_activation_email.html', {
				'user': user,
				'domain': current_site.domain,
				'uid': urlsafe_base64_encode(force_bytes(user.pk)),
				'token': account_activation_token.make_token(user),
			})
			user.email_user(subject, message)

			messages.info(request, ('Please Confirm your email to complete registration. A confirmation link has been sent at your provided email address.'))

			return redirect('login-page')

		return render(request, self.template_name, {'form': form})

class ActivateAccount(View): #this function will check that the account shoud be active or ready to use only when users click on the confirmation link sent on its email id when he registers first time.

	def get(self, request, uidb64, token, backend='django.contrib.auth.backends.ModelBackend', *args, **kwargs):
		try:
			uid = force_text(urlsafe_base64_decode(uidb64))
			user = User.objects.get(pk=uid)
		except (TypeError, ValueError, OverflowError, User.DoesNotExist):
			user = None

		if user is not None and account_activation_token.check_token(user, token):
			user.is_active = True
			user.profile.email_confirmed = True
			user.save()
			login(request, user, backend='django.contrib.auth.backends.ModelBackend')
			messages.success(request, ('Your account has been confirmed.'))
			return redirect('blog:blog-home')
		else:
			messages.warning(request, ('The confirmation link was invalid, possibly because it has already been used.'))
			return redirect('blog:blog-home')

@login_required#(redirect_field_name='users/profile') #this will check that user is logged in or not to look at his profile
def profile(request):
	if request.method == 'POST':
		u_form = UserUpdateForm(request.POST, instance=request.user)
		p_form = ProfileUpdateForm(request.POST,
								   request.FILES,
								   instance=request.user.profile)
		if u_form.is_valid() and p_form.is_valid():
			u_form.save()
			p_form.save()
			messages.success(request, f'Your profile has been updated successfully!')
			return redirect('users:profile-page')
	else:
		u_form = UserUpdateForm(instance=request.user)
		p_form = ProfileUpdateForm(instance=request.user.profile)

	context =  {
		'u_form': u_form,
		'p_form': p_form
	}
	return render(request, 'users/profile.html',context)

users/templates/users/account_activation_email.html
{% csrf_token %}
{% autoescape off %} 
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}
{% endautoescape %}

users/templates/users/login.html
<!-- this line here extends means that we want to show this login page in the base2.html where {% block content %} this is written and load crispy-forms means that we want to use crsipy_forms in our html page -->
{% extends 'blog/base2.html' %}
{% load crispy_forms_tags %}
{% block content %}

	<!-- <h1> Hello this is my second django site project</h1> -->
	


	<div class="container-fluid mt-4 col-xs-8" style="margin-left: 25%;">
	<div class = 'content-section'>
		<div class="container-fluid ">
			<div class="row ml-1">
				<div class="col md-4">
					<!-- this csrf token is for security purpose in django and whenever we use this form anywhere in our html pages then after form first line we have to write csrf_token always-->
		<form action = "" method = "POST" >{% csrf_token %}
			<fieldset class ="form-group" >
				<legend class ="border-bottom mb-4">
					Sign in manually
				</legend>
				<!-- {{ form.as_p }} we were using this coding block when we dont use crispy forms -->
				<!-- crispy is django filter here -->
				{{ form|crispy }}

			</fieldset>
			<div class="form-group">
			<button class="btn btn-primary" type = "submit">Login</button>	
			<small class="text-muted ml-2">
				<a href="{% url 'password_reset' %}">Forgot Password?</a>
			</small>
			</div>	

				</div>
			<!-- <p>-- OR --</p> -->
			<!-- <div class="mb-2" style="width: 100%; height: 20px; border-bottom: 1px solid black; text-align: center">
			  <span style="font-size: 20px; background-color: #F3F5F6; padding: 0 5px;">
			    Or Login From
			  </span>
			</div> -->
			<div class="ml-4" style=" 
  border-left: 2px solid black;
  height: 300px; position: relative;">
			  	<span style="position: absolute;
  top: 50%;
  transform: translate(-50%, -50%);
  background-color: #f1f1f1;
  border: 1px solid #ccc;
  border-radius: 50%;
  padding: 8px 10px;">OR</span>
  			</div>
			
			<div class="col md-4 ml-3">

				<p class="h4 text-center">Login With:</p>

				
				<ul class="text-center  " style="margin-top: 85px;" >
					<!-- this href means that we want to make this button special with social authentication purpose.   -->
					<li ><a href="{% url 'social:begin' 'github' %}">
						<button type="button" name="button" class="btn btn-dark mr-1 mb-2" ><i class="fa fa-github fa-fw mr-1"></i>Log In With Github</button>
					</a></li>

					<li><a href="{% url 'social:begin' 'google-oauth2' %}">
						<button type="button" name="button" class="btn btn-danger mr-1 mb-2" ><i class="fa fa-google fa-fw mr-1"></i>Log In With Google+</button>
					</a></li>

					<li><a href="{% url 'social:begin' 'facebook' %}">
						<button type="button" name="button" class="btn btn-primary mb-2" ><i class="fa fa-facebook fa-fw mr-1"></i>Log In With Facebook</button>
					</a></li>

				</ul>
			</div>
			
			<!-- <div> -->
		</form>
			</div>
		</div>
		<div class="border-top pt-3">
			<small class = "text-muted">
				Need An Account? <a class = "ml-2" href="{% url 'users:register-page' %}"><button class="btn btn-info btn-sm"> Sign Up Now </button></a>
			</small>
		</div>

	</div> 
</div>



	

{% endblock content %}

users/templates/users/logout.html
{% extends 'blog/base4.html' %}
{% block content %}
	<!-- <h1> Hello this is my second django site project</h1> -->
	<h2>Thanks for spending time with me. See you soon&#128521;</h2>
	<div class="border-top pt-3">
		<small class = "text-muted">
			<button type="submit" value="Log In Again" class="btn btn-outline-primary"><a  href="{% url 'login-page' %}">Wanna Login Again?</a></button>
		</small>
	</div>
{% endblock content %}

users/templates/users/password_reset.html
{% extends 'blog/base4.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<!-- <h1> Hello this is my second django site project</h1> -->

	<div class = 'content-section' >
		<form action = "" method = "POST" >{% csrf_token %}
			<fieldset class ="form-group" >
				<legend class ="border-bottom mb-4">
					Reset Password
				</legend>
				<!-- {{ form.as_p }} we were using this coding block when we dont use crispy forms -->
				{{ form|crispy }}

			</fieldset>
			<div class="form-group">
			<button class="btn btn-outline-info" type = "submit">Request Password Reset</button>	
			</div>	
		</form>
	</div>

{% endblock content %}

users/templates/users/password_reset_complete.html
{% extends 'blog/base4.html' %}
{% block content %}
	<div class="alet alert-info">
		Your password has been changed successfully.
	</div>
	<a href="{% url 'login-page' %}">Sign In Here</a>
{% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends 'blog/base4.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<!-- <h1> Hello this is my second django site project</h1> -->

	<div class = 'content-section' >
		<form action = "" method = "POST" >{% csrf_token %}
			<fieldset class ="form-group" >
				<legend class ="border-bottom mb-4">
					Reset Password
				</legend>
				<!-- {{ form.as_p }} we were using this coding block when we dont use crispy forms -->
				{{ form|crispy }}

			</fieldset>
			<div class="form-group">
			<button class="btn btn-outline-info" type = "submit">Reset Password</button>	
			</div>	
		</form>
	</div>

{% endblock content %}

users/templates/users/password_reset_done.html
{% extends 'blog/base4.html' %}
{% block content %}
	<div class="alet alert-info">
		An email has been successfully sent with instructions to reset your password.
	</div>
{% endblock content %}

users/templates/users/profile.html
{% extends 'blog/base1.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<!-- <h1> Hello this is my second django site project</h1> -->
	<!-- <h1>{{ user.username }}</h1> -->
		<div class="container-fluid" style="margin-left: 23%;">
	    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
      <!-- FORM HERE -->
      <form action = "" method = "POST" enctype="multipart/form-data" >{% csrf_token %}
		<fieldset class ="form-group">
			<legend class ="border-bottom mb-4">
				Profile Info
			</legend>
			<!-- {{ form.as_p }} we were using this coding block when we dont use crispy forms -->
			{{ u_form|crispy }}
			{{ p_form|crispy }}

		</fieldset>
		<div class="form-group">
		<button class="btn btn-outline-info" type = "submit">Update</button>	
		</div>	
	</form>
    </div>
</div>
{% endblock content %}

users/templates/users/register.html
{% extends 'blog/base3.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<!-- <h1> Hello this is my second django site project</h1> -->
	<div class="container-fluid mt-4 col-xs-8" style="margin-left: 25%;">
	<div class = 'content-section' >
		<div class="container-fluid" >
			<div class="row ml-1">
				<div class="col md-6">
		<form action = "" method = "POST" >{% csrf_token %}
			<fieldset class ="form-group" >
				<legend class ="border-bottom mb-4">
					Join ParthBook Today
				</legend>
				<!-- {{ form.as_p }} we were using this coding block when we dont use crispy forms -->
				

				{{ form|crispy }}

				

				
			</fieldset>
			<div class="form-group">
			<button class="btn btn-primary" type = "submit"> Sign Up</button>	
			</div>	
				</div>

				<div class="ml-4" style=" 
	  border-left: 2px solid black;
	  height: 800px; position: relative;">
				  	<span style="position: absolute;
	  top: 50%;
	  transform: translate(-50%, -50%);
	  background-color: #f1f1f1;
	  border: 1px solid #ccc;
	  border-radius: 50%;
	  padding: 8px 10px;">OR</span>
	  			</div>

	  			<div class="col md-6">
	  				<p class="h4 text-center">Register With:</p>
				
				<ul class="text-center  " style="margin-top: 300px;" >
					<li ><a href="{% url 'social:begin' 'github' %}">
						<button type="button" name="button" class="btn btn-dark mr-1 mb-2" ><i class="fa fa-github fa-fw mr-1"></i>Log In With Github</button>
					</a></li>

					<li><a href="{% url 'social:begin' 'google-oauth2' %}">
						<button type="button" name="button" class="btn btn-danger mr-1 mb-2" ><i class="fa fa-google fa-fw mr-1"></i>Log In With Google+</button>
					</a></li>

					<li><a href="{% url 'social:begin' 'facebook' %}">
						<button type="button" name="button" class="btn btn-primary mb-2" ><i class="fa fa-facebook fa-fw mr-1"></i>Log In With Facebook</button>
					</a></li>

				</ul>
			</div>

		
		</form>
	</div>
</div>
		<div class="border-top pt-3">
			<small class = "text-muted">
				Already Have An Account? <a class = "ml-2" href="{% url 'login-page' %}"><button class="btn btn-info btn-sm"> Sign In </button></a>
			</small>
		</div>

	</div>
</div>

{% endblock content %}